In [3]:
import numpy as np

myList = [1, 2, 3, 4, 5]
ma = np.array(myList)
print(ma)
print(type(ma))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
books = np.array(["R", "Python", "Spark", "Hadoop", "SAS"])

print(books)
print(books[2])
print(type(books))

['R' 'Python' 'Spark' 'Hadoop' 'SAS']
Spark
<class 'numpy.ndarray'>


In [8]:
np.random.random(size=20)

array([0.87941754, 0.70697881, 0.50479861, 0.91971468, 0.71068577,
       0.57905071, 0.5316378 , 0.98931888, 0.94415502, 0.7195182 ,
       0.54723629, 0.7237551 , 0.17331025, 0.46635421, 0.88113723,
       0.78255181, 0.216637  , 0.41698796, 0.20488085, 0.57485085])

In [6]:
np.random.rand(2, 3)

array([[0.19021372, 0.9224984 , 0.52123474],
       [0.86573556, 0.6536535 , 0.02238962]])

In [9]:
np.random.randn(2, 3)

array([[-1.20678291,  0.83039179, -0.56525399],
       [ 1.42827919, -0.58837998, -0.28700009]])

In [6]:
print(np.random.randint(2, 20)) #returns one value
print(np.random.randint(10, 100, size=15)) #return array of size 15

2
[40 71 95 46 93 14 88 85 52 80 60 19 30 53 57]


In [15]:
range(10) #0-9
range(1, 10) #1-9
range(1, 10, 2) #1-9 with increment 2

even_nums = np.arange(start=10, stop=100, step=2)
print(even_nums)
print(type(even_nums))

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56
 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96 98]
<class 'numpy.ndarray'>


In [19]:
nums = np.linspace(start=10, stop=100, num=10)
print(nums)
print(type(nums))

[ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
<class 'numpy.ndarray'>


In [20]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [21]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [25]:
matrix = np.empty((3, 3), dtype=object)
print(matrix)

[[None None None]
 [None None None]
 [None None None]]


In [27]:
matrix = np.full((3, 3), fill_value=11)
print(matrix)

[[11 11 11]
 [11 11 11]
 [11 11 11]]


In [30]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [36]:
print(np.eye(N=5, M=5, k=0))
print()
print(np.eye(N=5, M=5, k=2))
print()
print(np.eye(N=5, M=5, k=-2))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

[[0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [38]:
books = np.array([("R", "Python", "Spark", "Hadoop", "SAS"), (500, 600, 800, 700, 1000)])

print(books)
print("The shape of books is ", books.shape)
print("The size of books is ", books.size)

[['R' 'Python' 'Spark' 'Hadoop' 'SAS']
 ['500' '600' '800' '700' '1000']]
The shape of books is  (2, 5)
The size of books is  10


In [40]:
ar_nums = np.array([(2.3, 5.6, 4.5), (1, 3.8, 8.2)])

print("Data type of array elements is ", ar_nums.dtype)

Data type of array elements is  float64


In [42]:
print(ma.ndim)
print(books.ndim)

1
2


In [46]:
employee = np.array([("Sachin", 34), ("John", 25), ("Vinayak", 22)])
print(employee)

#Num of elements should not change
reshaped_employee = employee.reshape(6, 1)
print("\n", reshaped_employee)

[['Sachin' '34']
 ['John' '25']
 ['Vinayak' '22']]

 [['Sachin']
 ['34']
 ['John']
 ['25']
 ['Vinayak']
 ['22']]


In [49]:
print(employee[-1]) #last row
print("John age is ",employee[1, 1])
print("Sachin age is ",employee[0][1])

['Vinayak' '22']
John age is  25
Sachin age is  34


In [10]:
weight = np.array([73, 45, 78, 92, 51, 88])

print("4th and 5th elements are ", weight[3:5])
print("Every 3rd element is start from 1st ", weight[0::3])
print("Elements before 92 ", weight[:4])

4th and 5th elements are  [92 51]
Every 3rd element is start from 1st  [73 92]
Elements before 92  [73 45 78 92]


In [58]:
age = np.array([(73, 68, 54), (21, 36, 19)])

print(age)
print("1st row 1st 2 cols are ", age[0, :2])
print("2nd row last 2 cols are ", age[1, 1:])

[[73 68 54]
 [21 36 19]]
1st row 1st 2 cols are  [73 68]
2nd row last 2 cols are  [36 19]


In [59]:
f_ar = np.array([1, 2, 3, 5])
s_ar = np.array([11, 12, 13, 14, 15])

f_ar + s_ar

ValueError: operands could not be broadcast together with shapes (4,) (5,) 

In [77]:
odd_num = np.array([1, 2, 3, 5])
even_num = np.array([12, 14, 16, 18])

addition = odd_num + even_num
subtraction = odd_num - even_num
multiplication = odd_num * even_num

print("Odd ", odd_num)
print("Even ", even_num)
print("Addition ", addition)
print("Subtraction ", subtraction)
print("Updated array", odd_num * 2)
print("Multiplication ", multiplication)
print("Dot Product ", odd_num.dot(even_num))

Odd  [1 2 3 5]
Even  [12 14 16 18]
Addition  [13 16 19 23]
Subtraction  [-11 -12 -13 -13]
Updated array [ 2  4  6 10]
Multiplication  [12 28 48 90]
Dot Product  178


In [62]:
salary = np.array([40000, 38000, 52000, 60000, 30000, 90000])
print("Min Salary ", salary.min())
print("Max Salary ", salary.max())
print("Salary variance ", salary.var())
print("Std. Dev Salary ", salary.std())

Min Salary  30000
Max Salary  90000
Salary variance  388555555.5555555
Std. Dev Salary  19711.812589296693


In [64]:
print("Square of the numbers are ", np.square(odd_num))

Square of the numbers are  [ 1  4  9 25]


In [66]:
print("Power of the numbers raise to 3 are ", np.power(odd_num, 3))

Power of the numbers raise to 3 are  [  1   8  27 125]


In [84]:
employee = np.array([("Sachin", 34), ("John", 25), ("Vinayak", 22)])
print("Original array: \n", employee)

transposed_employee = np.transpose(employee)
print("Transposed array: \n", transposed_employee)

odd = np.array([(1, 2, 3, 5), (8, 4, 2, 6)])
trans_odd = np.transpose(odd)
print("Dot Product: \n", odd.dot(trans_odd))

Original array: 
 [['Sachin' '34']
 ['John' '25']
 ['Vinayak' '22']]
Transposed array: 
 [['Sachin' 'John' 'Vinayak']
 ['34' '25' '22']]
Dot Product: 
 [[ 39  52]
 [ 52 120]]


In [73]:
print("Concatenated array: ", np.concatenate([odd_num, even_num]))

Concatenated array:  [ 1  2  3  5 12 14 16 18]


In [13]:
employee = np.array([("Sachin", 34), ("John", 25), ("Vinayak", 22)])
consultant = np.array([("Harry", 45), ("Ejaz", 41)])

all_emp = np.concatenate([employee, consultant])
print("All Employees: \n", all_emp)

All Employees: 
 [['Sachin' '34']
 ['John' '25']
 ['Vinayak' '22']
 ['Harry' '45']
 ['Ejaz' '41']]


In [79]:
age = np.array([(73, 68, 54), (21, 36, 19)])

print("Array Flattened ", np.ndarray.flatten(age))

Array Flattened  [73 68 54 21 36 19]


In [80]:
newbooks = np.array(["R", "Python", "Spark", "Hadoop", "SAS"])

for book in newbooks:
    print(book)

R
Python
Spark
Hadoop
SAS


In [82]:
books = np.array([("R", "Python", "Spark", "Hadoop", "SAS"), (500, 600, 800, 700, 1000)])

for i in books:
    print(i)

['R' 'Python' 'Spark' 'Hadoop' 'SAS']
['500' '600' '800' '700' '1000']


In [83]:
for i in books:
    for j in i:
        print(j)

R
Python
Spark
Hadoop
SAS
500
600
800
700
1000
